# This is a basic workflow to help you get started with Actions

name: resume-front-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: dev
  pull_request:
    branches: dev

  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  # jobs:
  #   # This workflow contains a single job called "build"
  #   build:
  #     # The type of runner that the job will run on
  #     runs-on: ubuntu-latest

  #     # Steps represent a sequence of tasks that will be executed as part of the job
  #     steps:
  #       - name: Checkout source code
  #         uses: actions/checkout@master
  #       # Runs a set of commands using the runners shell
  #       - name: Code Deploy
  #         env:
  #           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         run: |
  #           aws s3 cp \
  #             --recursive \
  #             --region ap-northeast-2 \
  #             dist s3://local-festival-s3
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout source code
          uses: actions/checkout@master

        # 실행 속도를 빠르게 하기 위해 설치된 Node 모듈을 캐시하도록 설정합니다.
        - name: Cache node modules
          uses: actions/cache@v2
          with:
            path: ~/.npm
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-node-

        - name: Install Dependencies
          run: yarn

        - name: Build
          run: yarn build
          env:
            CI: ''

        - name: Deploy
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          run: |
            aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            build s3://local-festival-s3
