name: client-deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches: -main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./client

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: check list
        run: ls -al
      - name: check pwd
        run: pwd
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install packages
        run: npm ci
      - name: Create env file
        run: |
          touch .env
          echo REACT_APP_SERVER_URL=${{secrets.REACT_APP_SERVER_URL}} >> .env
          cat .env

      - name: Build
        run: npm run build
        env:
          CI: ''
      - name: check ls
        run: ls -al

      - name: deploy
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: 'locoloco.tk'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: './client/build'
