name: server-deploy

on:
  push:
    branches:
      - dev
  pull_request:
    branches: -dev
    

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./server

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: 'ubuntu'
          key: ${{ secrets.SSH_KEY }}
          script: |
            pwd
